export enum types {
  GLOBAL_DATA_RESULT = 'GLOBAL_DATA_RESULT',
  GLOBAL_DATA_LOADING = 'GLOBAL_DATA_LOADING',
  GLOBAL_DATA_ERROR = 'GLOBAL_DATA_ERROR'
}

export type TTypes = types.GLOBAL_DATA_RESULT | types.GLOBAL_DATA_LOADING | types.GLOBAL_DATA_ERROR
